/** test/crx_v3 - TAP harness for CRX v3 (Hatanaka) decompression.
 * Copyright 2025 Michael Poole.
 * SPDX-License-Identifier: MIT-Modern-Variant
 */

#include "rinex/rinex.h"
#include <stdlib.h>
#include <tap.h>

/* Generated by `xxd -i -l 23712 abmf.crx`, with variable names edited. */
#include "bin/abmf00glp_crx.h"

/* Tests based on ABMF00GLP_R_20201890000_01D_30S_MO.crx, comparing
 * decompressed values against the uncompressed .rnx reference.
 */
void test_abmf00glp_crx(void)
{
    struct rinex_stream *crx;
    struct rinex_parser *p;
    const char *msg;
    rinex_error_t err;
    unsigned int ofs, ii;

    /* 8 tests: open and verify header */
    p = NULL;
    crx = rinex_buffer_stream(abmf_crx, abmf_crx_len);
    msg = rinex_open(&p, crx);
    ok(msg == NULL, "rinex_open() for CRX succeeded");
    if (!p) BAIL_OUT();
    ok(p->n_obs['G' & 31] == 18, "18 observables for GPS");
    ok(p->n_obs['E' & 31] == 20, "20 observables for Galileo");
    ok(p->n_obs['S' & 31] == 8, "8 observables for SBAS");
    ok(p->n_obs['R' & 31] == 20, "20 observables for GLONASS");
    ok(p->n_obs['C' & 31] == 12, "12 observables for BeiDou");
    ok(p->n_obs['J' & 31] == 12, "12 observables for QZSS");
    ok(p->n_obs['I' & 31] == 4, "4 observables for NavIC");

    /* 10 tests: first epoch metadata */
    err = p->read(p);
    ok(err == RINEX_SUCCESS, "CRX read() #1 succeeded");
    ok(p->epoch.yyyy_mm_dd == 20200707, "date is 2020-07-07");
    ok(p->epoch.hh_mm == 0, "time-of-day is 00:00");
    ok(p->epoch.flag == '0', "epoch flag is 0");
    ok(p->epoch.sec_e7 == 0, "seconds is 0.0000000");
    ok(p->epoch.n_sats == 42, "first epoch has 42 satellites");
    ok(p->epoch.clock_offset == 0, "clock offset is 0");
    ok(p->sats[0].system == 'E' && p->sats[0].number == 4, "first sat is E04");
    ok(p->sats[1].system == 'G' && p->sats[1].number == 15, "second sat is G15");
    ok(p->sats[41].system == 'C' && p->sats[41].number == 22, "last sat is C22");

    /* 23 tests: first satellite (E04) observations — same as rinex_v3 test */
    ofs = p->sats[0].obs_0;
    ok(p->obs[ofs+0] == 28541439844, "E04 obs 1 is 28541439.844");
    ok(p->lli[ofs+0] == ' ', "E04 first LLI is blank");
    ok(p->ssi[ofs+0] == '5', "E04 first SSI is 5");
    ok(p->obs[ofs+1] == 149986288817, "E04 obs 2 is 149986288.817");
    ok(p->lli[ofs+1] == '0', "E04 second LLI is 0");
    ok(p->obs[ofs+2] == 1175101, "E04 obs 3 is 1175.101");
    ok(p->obs[ofs+3] == 35700, "E04 obs 4 is 35.700");
    ok(p->obs[ofs+4] == 28541441120, "E04 obs 5 is 28541441.120");
    ok(p->obs[ofs+5] == 121742127938, "E04 obs 6 is 121742127.938");
    ok(p->obs[ofs+6] == 953962, "E04 obs 7 is 953.962");
    ok(p->obs[ofs+7] == 40164, "E04 obs 8 is 40.164");
    ok(p->obs[ofs+8] == 28541441048, "E04 obs 9 is 28541441.048");
    ok(p->obs[ofs+9] == 112002756211, "E04 obs 10 is 112002756.211");
    ok(p->obs[ofs+10] == 877350, "E04 obs 11 is 877.350");
    ok(p->obs[ofs+11] == 39658, "E04 obs 12 is 39.658");
    ok(p->obs[ofs+12] == 28541440314, "E04 obs 13 is 28541440.314");
    ok(p->obs[ofs+13] == 114924561309, "E04 obs 14 is 114924561.309");
    ok(p->obs[ofs+14] == 900319, "E04 obs 15 is 900.319");
    ok(p->obs[ofs+15] == 40849, "E04 obs 16 is 40.849");
    ok(p->obs[ofs+16] == 28541440985, "E04 obs 17 is 28541440.985");
    ok(p->obs[ofs+17] == 113463662329, "E04 obs 18 is 113463662.329");
    ok(p->obs[ofs+18] == 888852, "E04 obs 19 is 888.852");
    ok(p->obs[ofs+19] == 43227, "E04 obs 20 is 43.227");

    /* 18 tests: second satellite (G15) observations */
    ofs = p->sats[1].obs_0;
    ok(p->obs[ofs+0] == 21062787884, "G15 obs 1 is 21062787.884");
    ok(p->obs[ofs+1] == 110685754321, "G15 obs 2 is 110685754.321");
    ok(p->obs[ofs+2] == -1567275, "G15 obs 3 is -1567.275");
    ok(p->obs[ofs+3] == 48530, "G15 obs 4 is 48.530");
    ok(p->obs[ofs+4] == 21062787634, "G15 obs 5 is 21062787.634");
    ok(p->obs[ofs+5] == 50327, "G15 obs 6 is 50.327");
    ok(p->obs[ofs+6] == 21062785399, "G15 obs 7 is 21062785.399");
    ok(p->obs[ofs+7] == 86248658482, "G15 obs 8 is 86248658.482");
    ok(p->obs[ofs+8] == -1221255, "G15 obs 9 is -1221.255");
    ok(p->obs[ofs+9] == 50327, "G15 obs 10 is 50.327");
    ok(p->obs[ofs+10] == 21062786045, "G15 obs 11 is 21062786.045");
    ok(p->obs[ofs+11] == 86248665487, "G15 obs 12 is 86248665.487");
    ok(p->obs[ofs+12] == -1221317, "G15 obs 13 is -1221.317");
    ok(p->obs[ofs+13] == 44877, "G15 obs 14 is 44.877");
    for (ii = 14; ii < 18; ++ii)
        ok(p->obs[ofs+ii] == 0, "G15 obs N is zero");

    /* 11 tests: second epoch (delta-decompressed) */
    err = p->read(p);
    ok(err == RINEX_SUCCESS, "CRX read() #2 succeeded");
    ok(p->epoch.yyyy_mm_dd == 20200707, "epoch 2 date is 2020-07-07");
    ok(p->epoch.sec_e7 == 300000000, "epoch 2 seconds is 30.0000000");
    ok(p->epoch.n_sats == 42, "epoch 2 has 42 satellites");
    ofs = p->sats[0].obs_0;
    ok(p->obs[ofs+0] == 28534747227, "E04 epoch2 obs 1 is 28534747.227");
    ok(p->obs[ofs+1] == 149951119017, "E04 epoch2 obs 2 is 149951119.017");
    ok(p->obs[ofs+2] == 1170082, "E04 epoch2 obs 3 is 1170.082");
    ok(p->obs[ofs+3] == 34638, "E04 epoch2 obs 4 is 34.638");
    ok(p->ssi[ofs+0] == '5', "E04 epoch2 SSI is 5");
    ok(p->lli[ofs+0] == ' ', "E04 epoch2 LLI is blank");
    ok(p->sats[0].system == 'E' && p->sats[0].number == 4, "epoch2 first sat is E04");

    /* 3 tests: third epoch (00:01:00.0) */
    err = p->read(p);
    ok(err == RINEX_SUCCESS, "CRX read() #3 succeeded");
    ok(p->epoch.n_sats == 42, "epoch 3 has 42 satellites");
    ok(p->epoch.hh_mm == 1, "epoch 3 time is 00:01");

    p->destroy(p);
    crx->destroy(crx);
}

int main(int argc, char *argv[])
{
    plan(73);

    test_abmf00glp_crx();

    done_testing(); (void)argc; (void)argv;
}
